### ISSUE TITLE
windows compiled failed

### ISSUE THREAD

**Issue by Roger8** [PabloPicose/OpenCVNodeEditor#1]
This is a great work for computer vision. Thanks for your code.
It failed when i compiled this code .  The error info :
`1>DropGraphicsView.obj : error LNK2019: unresolved external symbol "public: __cdecl QtNodes::CreateCommand::CreateCommand(class QtNodes::BasicGraphicsScene *,class QString,class QPointF const &)" (??0CreateCommand@QtNodes@@QEAA@PEAVBasicGraphicsScene@1@VQString@@AEBVQPointF@@@Z) referenced in function "public: void __cdecl DropGraphicsView::placeNodeInScene(class QString const &,class QPoint const &)" (?placeNodeInScene@DropGraphicsView@@QEAAXAEBVQString@@AEBVQPoint@@@Z)
1>ComputerVisionBlueprint-main\build\Debug\ComputerVisionBlueprint.exe : fatal error LNK1120: 1 unresolved externals`

additional appendices :` lib\Release\QtNodes.lib;`
include : 
```
D:\Downloads\ComputerVisionBlueprint-main\build\ComputerVisionBlueprint_autogen\include_Release
D:\Downloads\ComputerVisionBlueprint-main\src
D:\Downloads\ComputerVisionBlueprint-main\3rdparty\nodeeditor\src
D:\Downloads\ComputerVisionBlueprint-main\3rdparty\nodeeditor\include\QtNodes\internal
D:\Downloads\ComputerVisionBlueprint-main\3rdparty\nodeeditor\include
```
maybe this is a dynamic dll problem . How can i fix it ?

**Comment by Roger8** [comment]
fix `UndoCommands.hpp` line to this `class NODE_EDITOR_PUBLIC CreateCommand : public QUndoCommand`  , it worked.

**Comment by PabloPicose** [comment]
So the error was in the QtNodes library when compiling on windows?

**Comment by Roger8** [comment]
> So the error was in the QtNodes library when compiling on windows?

yes, QtNodes link error . `CreateCommand` was not in QtNodes dll.
